[window]
decorations = "Full"
decorations_theme_variant = "Dark"
padding.x = 2
padding.y = 2


[font]
normal = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Bold" }
italic = { family = "Fira Code", style = "Italic" }
bold_italic = { family = "Fira Code", style = "Bold Italic" }
size = 7


[colors.primary]
background = "#000000"


[cursor]
style = "underline"
